# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  node: circleci/node@5.0.0
  aws-s3: circleci/aws-s3@3.0.0

jobs:
  # Below is the definition of your job to build and test your app, you can rename and customize it as you want.
  build-and-deploy-symmv2:
    # These next lines define a Docker executor: https://circleci.com/docs/2.0/executor-types/
    # You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # A list of available CircleCI Docker Convenience Images are available here: https://circleci.com/developer/images/image/cimg/node
    docker:
      - image: cimg/node:16.10
    steps:
      # Checkout the code as the first step.
        - checkout
        # Next, the node orb's install-packages step will install the dependencies from a package.json.
        # The orb install-packages step will also automatically cache them for faster future runs.
        - node/install-packages:
            # If you are using yarn, change the line below from "npm" to "yarn"
            pkg-manager: npm
            override-ci-command: npm install
        - run:
            name: Setting Env Variable
            command: |
              echo "AWS_BUCKET_LOCATION_V2"
              echo $AWS_BUCKET_LOCATION_V2
              echo $CIRCLE_BRANCH
              echo $CIRCLE_BUILD_NUM-$APP_NETWORK_CELO_ID
              touch .env
              echo "VUE_APP_ENV=production
              VUE_APP_DOMAIN=$APP_DOMAIN
              VUE_APP_IPFS_NODE=cloudflare-ipfs.com
              VUE_APP_NETWORK=$APP_CHAIN_ID_C
              VUE_APP_BLOCKNATIVE_DAPP_ID=032e2fb8-6c66-46a5-bf1c-a049ac7eded2
              VUE_APP_PORTIS_DAPP_ID=3f1c3cfc-7dd5-4e8a-aa03-71ff7396d9fe
              VUE_APP_FATHOM_SITE_ID=xxx
              VUE_APP_GA_ID=$VUE_APP_GA_ID
              VUE_APP_DOMAIN=$APP_NETWORK_CELO_ID
              SUBGRAPH_URL=$SUBGRAPH_URL_SYMM_V2
              VUE_APP_BUILD_NUMBER=$CIRCLE_BUILD_NUM" > .env
        - run:
            name: Setting appspec
            command: |
              touch appspec.yml
              echo "version: 0.0
              os: windows
              files:
                - source: .
                  destination: $APPSPEC_DESTINATION" > appspec.yml      
        - run:
            name: Run Build
            command: npm run build
        - run:
            name: Compress Artifacts
            command: zip -qr $CIRCLE_BRANCH-$CIRCLE_BUILD_NUM-$APP_NETWORK_CELO_ID.zip ./dist appspec.yml
        - aws-s3/copy:
            from: $CIRCLE_BRANCH-$CIRCLE_BUILD_NUM-$APP_NETWORK_CELO_ID.zip 
            to: $AWS_BUCKET_LOCATION_V2 
        - run:    
            name: Iniitate Code-Deploy
            command: |
                echo "pushing to DEV..." 
                ID=$(aws deploy create-deployment \
                    --application-name $APP_NAME_V2 \
                    --deployment-config-name CodeDeployDefault.AllAtOnce \
                    --deployment-group-name $CODE_DEPLOYMENT_GROUP_DEV \
                    --s3-location bucket=symmetric-pools-ui-bucket,bundleType=zip,key=V2/$CIRCLE_BRANCH-$CIRCLE_BUILD_NUM-$APP_NETWORK_CELO_ID.zip \
                    --description "$GIT_COMMIT_MSG" \
                    --output text \
                    --query 'deploymentId')
                echo $ID      
                STATUS=$(aws deploy get-deployment --deployment-id $ID --output text --query 'deploymentInfo.status')
                echo "STATUS: $STATUS..."
                while [[ $STATUS == "Created" || $STATUS == "InProgress" || $STATUS == "Pending" || $STATUS == "Queued" || $STATUS == "Ready" ]]; do
                        echo "Status: $STATUS..."
                        STATUS=$(aws deploy get-deployment --deployment-id $ID --output text --query 'deploymentInfo.status')
                        sleep 5
                      done
                      if [[ $STATUS == "Succeeded" ]]; then
                        EXITCODE=0
                        echo "Deployment finished."
                      else
                        EXITCODE=1
                        echo "Deployment failed!"
                      fi
                      aws deploy get-deployment --deployment-id $ID
                      exit $EXITCODE
              

workflows:
  # Below is the definition of your workflow.
  # Inside the workflow, you provide the jobs you want to run, e.g this workflow runs the build-and-test job above.
  # CircleCI will run this workflow on every commit.
  # For more details on extending your workflow, see the configuration docs: https://circleci.com/docs/2.0/configuration-reference/#workflows
  Build-and-Deploy:
    jobs:
      - build-and-deploy-symmv2